export const INSTRUCTOR_REQUEST="INSTRUCTOR_REQUEST";
export const INSTRUCTOR_FAILURE="INSTRUCTOR_FAILURE";

export const INSTRUCTOR_SUCCESS="INSTRUCTOR_SUCCESS"
export const PATCH_INSTRUCTOR_SUCCESS="PATCH_INSTRUCTOR_SUCCESS"